workflows:
  react-native:
    name: React Native Build
    environment:
      react-native:
        version: 0.73.6 # Substitua pela versão do React Native que você está usando
      vars:
        NODE_ENV: "production"
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Run Android build
        script: cd android && ./gradlew assembleRelease
      - name: Run iOS build
        script: xcodebuild -workspace ios/juntin.xcworkspace -scheme juntin -configuration Release -sdk iphoneos archive -archivePath $PWD/build/juntin.xcarchive
    artifacts:
      - build/outputs/**/*.apk
      - build/juntin.xcarchive
    publishing:
      email:
        recipients:
          - antoniojoaossh@gmail.com
